version: '3' 
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./inside/nginx:/usr/share/nginx/html 

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: walid_password
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1