version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
      - api
    volumes:
      - ./nginx:/usr/share/nginx/html

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    volumes:
      - ./frontend/my_react_app:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: django_api
    volumes:
      - ./api:/app
    ports:
      - "8002:8002"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

volumes:
  db_data:
